version: '2'
volumes:
    sense-data:
services:
  influxdb:
    restart: always
    build: ./influxdb
    ports:
      - "9898:8096"
    volumes:
      - 'sense-data:/data'
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
        - 'GF_SESSION_PROVIDER=memory'
  sensor:
    build: ./sensor
    privileged: true
    restart: always
    depends_on:
     - influxdb
    volumes:
     - 'sense-data:/data'
  watchdog:
    build: ./watchdog
    restart: always
  homebridge:
    build: ./homebridge
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
  telegraf:
    build: ./telegraf
    restart: always
    cap_add:
      - SYS_ADMIN
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
