version: '2'
volumes:
    sense-data:
services:
  influxdb:
    restart: always
    image: drakeapps/balena-sense:influxdb
    build: ./influxdb
    ports:
      - "9898:8096"
    volumes:
      - 'sense-data:/data'
  grafana:
    restart: always
    image: drakeapps/balena-sense:grafana
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'HOME_DASHBOARD_UID=balenaSense'
        - 'GF_PATHS_DATA=/data/grafana'
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_SESSION_PROVIDER=memory'
        - 'GF_AUTH_ANONYMOUS_ENABLED=true'
  sensor:
    build: ./sensor
    image: drakeapps/balena-sense:sensor
    privileged: true
    restart: always
    depends_on:
     - influxdb
    volumes:
     - 'sense-data:/data'
    environment:
      - REMOTE_INFLUXDB=influx.xrho.com
      - DEVICE_NAME=garage
  watchdog:
    build: ./watchdog
    image: drakeapps/balena-sense:watchdog
    restart: always
  homebridge:
    build: ./homebridge
    image: drakeapps/balena-sense:homebridge
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
  telegraf:
    build: ./telegraf
    restart: always
    cap_add:
      - SYS_ADMIN
    environment: 
      - INFLUXDB_EXTERNAL_URL=influx.xrho.com
      - INFLUXDB_EXTERNAL_DB=garage
    depends_on: 
      - influxdb
      - sensor
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
