version: '2'
volumes:
    sense-data:
services:
  influxdb:
    restart: always
    build: ./influxdb
    ports:
      - "9898:8096"
    volumes:
      - 'sense-data:/data'
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80:3000"
    volumes:
      - 'sense-data:/data'
    depends_on:
      - influxdb
  sensor:
    build: ./sensor
    privileged: true
    restart: always
    depends_on:
     - influxdb
  watchdog:
    build: ./watchdog
    restart: always
  homebridge:
    build: ./homebridge
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
  upsmonitor:
    build: ./ups-monitor-settings
    privileged: true
    restart: always
    environment:
      - UDEV=1
    devices:
      - '/dev:/dev'
