version: '2'
volumes:
    sense-data:
services:
  influxdb:
    restart: always
    image: registry.gitlab.com/drakeapps/balena-sense/influxdb
    build: ./influxdb
    ports:
      - "9898:8096"
    volumes:
      - 'sense-data:/data'
  grafana:
    restart: always
    image: registry.gitlab.com/drakeapps/balena-sense/grafana
    build: ./grafana
    ports:
      - "80:3000"
    volumes:
      - 'sense-data:/data'
    depends_on:
      - influxdb
  sensor:
    build: ./sensor
    image: registry.gitlab.com/drakeapps/balena-sense/sensor
    privileged: true
    restart: always
    depends_on:
     - influxdb
  watchdog:
    build: ./watchdog
    image: registry.gitlab.com/drakeapps/balena-sense/watchdog
    restart: always
  homebridge:
    build: ./homebridge
    image: registry.gitlab.com/drakeapps/balena-sense/homebridge
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
  upsmonitor:
    build: ./ups-monitor-settings
    privileged: true
    restart: always
    environment:
      - UDEV=1
    devices:
      - '/dev:/dev'
