version: '2'
volumes:
    sense-data:
services:
  influxdb:
    restart: always
    image: drakeapps/balena-sense:influxdb
    build: ./influxdb
    ports:
      - "9898:8096"
    volumes:
      - 'sense-data:/data'
  grafana:
    restart: always
    image: drakeapps/balena-sense:grafana
    build: ./grafana
    ports:
      - "80:3000"
    volumes:
      - 'sense-data:/data'
    depends_on:
      - influxdb
  sensor:
    build: ./sensor
    image: drakeapps/balena-sense:sensor
    privileged: true
    restart: always
    depends_on:
     - influxdb
    environment: :
      - REMOTE_INFLUXDB=influx.xrho.com
      - DEVICE_NAME=garage
  watchdog:
    build: ./watchdog
    image: drakeapps/balena-sense:watchdog
    restart: always
  homebridge:
    build: ./homebridge
    image: drakeapps/balena-sense:homebridge
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
