name: Docker-arm32

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: grafana

jobs:

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platforms::linux/arm/v6,linux/arm/v7,linux/arm64
          echo ::set-output name=docker_username::drakeapps
          echo ::set-output name=docker_image::registry.gitlab.com/drakeapps/balena-sense:$IMAGE_NAME
          echo ::set-output name=version::${GITHUB_REF#refs/*/}
          echo ::set-output name=hash::${GITHUB_SHA}
      - name: Set up buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Docker Login
        if: success()
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.gitlab.com -u ${{ github.actor }} --password-stdin
      - name: Run Buildx (master)
        if: success() && contains(steps.prepare.outputs.version, 'master')
        run: |
          cd grafana && \
          docker buildx build \
            --output type=image,name=${{ steps.prepare.outputs.docker_image }},push=true \
            --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --tag "${{ steps.prepare.outputs.docker_image }}" \
            --file Dockerfile .